#ssh-agent w/ quiet (optional, set custom key if desired)
#zstyle :omz:plugins:ssh-agent agent-forwarding yes
#zstyle :omz:plugins:ssh-agent quiet yes
#zstyle :omz:plugins:ssh-agent identities ~/.ssh/kali

#place this in plugins to activate ssh-agetn
#ssh-agent

# Path to your oh-my-zsh installation.
export ZSH="/home/kali/.oh-my-zsh"


#New History file location allows us to back it up to github
HISTFILE="$HOME/.kali_history"
HISTSIZE=1000
SAVEHIST=2000
HISTSTAMPS="mm/dd/yyyy"
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt INC_APPEND_HISTORY_TIME

#history log function
    precmd() { eval 'if [ "$(id -u)" -ne 0 ]; then echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history -f)" >> ~/.logs/zsh-history-$(date "+%Y-%m-%d").log; fi' }
    

#zsh theme
ZSH_THEME="candy"

zstyle ':omz:update' mode auto      # update automatically without asking

plugins=(
colored-man-pages
sudo
zsh-autosuggestions
zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

#Custom ENV
export EDITOR=vim

#daily drivers for day to day tasks
alias http='sudo python3 -m http.server 80'
alias reload='. ~/.zshrc'
alias update='sudo apt-get update'
alias t='tmux -f ~/.tmux.conf'
alias i='sudo apt-get install'
alias public='curl ifconfig.me'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -'
alias nmap-quick='nmap -T4 -sC -sV -Pn -oA /home/kali/$TARGETNAME -p- $TARGETIP'
alias ffuf-quick='ffuf -u $URL -w /usr/share/seclists/Discovery/Web-Content/common.txt -o /home/kali/results.txt -mc 200 -fs 0'
alias whatweb-quick='whatweb $URL'

#basic shortcuts with a windows target flavor
alias cme='crackmapexec'
alias secretsdump='impacket-secretsdump'
alias ps-shell='cp /home/kali/nishang/Shells/Invoke-PowerShellTcpOneLine.ps1 .'
alias portscan='cp /home/kali/nishang/Scan/Invoke-PortScan.ps1'
alias nc='nc -nvlp'

